// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/Icons/LogoBachira copy 2.vue')['default']
    3: typeof import('./src/components/Icons/LogoBachira copy 3.vue')['default']
    4: typeof import('./src/components/Icons/LogoBachira copy 4.vue')['default']
    5: typeof import('./src/components/Icons/LogoBachira copy 5.vue')['default']
    BrandsSection: typeof import('./src/components/BrandsSection.vue')['default']
    copy: typeof import('./src/components/Icons/LogoBachira copy.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    IconsLogoAdidas: typeof import('./src/components/Icons/LogoAdidas.vue')['default']
    IconsLogoBachira: typeof import('./src/components/Icons/LogoBachira.vue')['default']
    IconsLogoBalenciaga: typeof import('./src/components/Icons/LogoBalenciaga.vue')['default']
    IconsLogoBukalapak: typeof import('./src/components/Icons/LogoBukalapak.vue')['default']
    IconsLogoGucci: typeof import('./src/components/Icons/LogoGucci.vue')['default']
    IconsLogoTokopedia: typeof import('./src/components/Icons/LogoTokopedia.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
