// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BrandsSection: typeof import('./src/components/BrandsSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    IconsLogoAdidas: typeof import('./src/components/icons/LogoAdidas.vue')['default']
    IconsLogoBachira: typeof import('./src/components/icons/LogoBachira.vue')['default']
    IconsLogoBalenciaga: typeof import('./src/components/icons/LogoBalenciaga.vue')['default']
    IconsLogoBukalapak: typeof import('./src/components/icons/LogoBukalapak.vue')['default']
    IconsLogoGucci: typeof import('./src/components/icons/LogoGucci.vue')['default']
    IconsLogoTokopedia: typeof import('./src/components/icons/LogoTokopedia.vue')['default']
    ProductsGrid: typeof import('./src/components/ProductsGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
